### ISSUE TITLE
Erros diversos

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#134]
- [x] Usuário caroline@castroli.com.br (senha Cm2021) não esta acessando nenhuma página, aparece uma tela diferente das demais vezes.
http://sistemacelic.net/admin/home#

![image](https://user-images.githubusercontent.com/60766925/113717808-622efb00-96c2-11eb-9e5e-7c5ad9ed6a5f.png)

**### Todos usuários:**
- [x] Pagina unidades:
Esta apresentando erro quando eu clico no menu lateral "unidades" (http://sistemacelic.net/admin/unidades), porem se entrar por empresas unidades, funciona (http://sistemacelic.net/admin/empresa/1/unidades).

![image](https://user-images.githubusercontent.com/60766925/113717091-a40b7180-96c1-11eb-9b71-57c75b756c84.png)

- [x] Dashboard:
Não esta aparecendo as pendencias.
![image](https://user-images.githubusercontent.com/60766925/113717187-c0a7a980-96c1-11eb-9e2d-1d97c618ee73.png)

- [x] Listagem geral de serviços:
Tambem esta apresentando erro (http://sistemacelic.net/admin/servicos);

![image](https://user-images.githubusercontent.com/60766925/113718119-b5a14900-96c2-11eb-9996-b3ed9596ee42.png)

- [x] Relatório completo de serviços:
Tambem esta apresentando erro (http://sistemacelic.net/admin/relatorio);
![image](https://user-images.githubusercontent.com/60766925/113718786-5f80d580-96c3-11eb-9d82-bb9bd2040108.png)

**Comment by castroli** [comment]
Usuário cliente (diego.castro@castroli.com.br senha Bkb@2021)
- [ ] Erro ao acessar qualquer serviço.

http://sistemacelic.net/cliente/servico/2687
![image](https://user-images.githubusercontent.com/60766925/113721426-e8990c00-96c5-11eb-992e-01d85aabc0e7.png)
http://sistemacelic.net/cliente/servico/2686
![image](https://user-images.githubusercontent.com/60766925/113721409-e5058500-96c5-11eb-8ec1-c22d39829a0a.png)
http://sistemacelic.net/cliente/servico/2685
![image](https://user-images.githubusercontent.com/60766925/113721471-f353a100-96c5-11eb-806b-bdeaff4808ad.png)

**Comment by fullcontent** [comment]
@castroli 

Resolvido. 

Problema na configuração PHP da Locaweb após as mudanças de ontem no disparo de emails.
