### ISSUE TITLE
Melhoria Pendência

### ISSUE THREAD

**Issue by castroli** [fullcontent/sistemacelic#326]
@fullcontent 
Peço incluir a opção de vincular uma pendência a outra pendência do mesmo processo.

**Comment by fullcontent** [comment]
@castroli 

![image](https://user-images.githubusercontent.com/6120413/219254040-bd16ed8d-adce-4858-8b49-2ec45d084b99.png)

A pendência poderá ser vinculada a mais de uma pendência, ou somente a uma?

**Comment by castroli** [comment]
@fullcontent, 
Conforme mandei no whatsApp, me posicionei errado, mas a tua ideia tbm é estremamente util. 
Respondendo a tua pergunta, poderá ser vinculada a mais de uma pendência!
Aproveito para incluir o pedido de também vincular a uma pendência de outro processo (sempre será da mesma unidade).

**Comment by castroli** [comment]
@fullcontent 
Qual a estimativa de prazo para atender este chamado?

**Comment by fullcontent** [comment]
### To-do list

- [ ] Api para buscar pendencias da mesma unidade
- [ ] Inserir campo de vinculo de pendência com busca por nome
- [ ] Criar banco de dados de vinculo de pendências
- [ ] Criar regra de alteração de responsabilidade da pendência vinculada para a pendencia principal

**Comment by castroli** [comment]
Segue lista atualizada.

"Castro"
--
Adequação em projeto
Comunicar cliente
Contato com órgão
Documental
Elaboração
Emissão de taxa
Montar processo
Pagamento de taxa
Pedido de prazo
Protocolar
Protocolar reentrada
RT
Tramitação interna

Responsabilidade   "Cliente"
--
Adequação física
Adequação em projeto
Documental
Em análise
Pagamento de taxa
Retorno cliente

Responsabilidade   "Órgão"
--
Em análise
Emissão de alvará
Retorno órgão

Pendência "Vinculada"
Vinculado

**Comment by fullcontent** [comment]
- [ ] Atualizar lista de nomenclatura de pendencias
